Add docstrings
MarcoGorelli/narwhals pull request #32
Opened 2024-03-28 18:52 UTC by frnmst

- Add more docstrings in `narwhals.dataframe.DataFrame` class
- Fix indentation in pre-commit file

2024-03-29 11:18 UTC, MarcoGorelli requested changes
These docstrings are great, thank you so much @frnmst !

Looks like CI is failing with
```
E   ValueError: line 29 of the doctest for narwhals.dataframe.DataFrame.group_by has an invalid option: '+IGNORE_RESULT'
```

Just got some minor comments

2024-03-29 11:18 UTC, MarcoGorelli commented on narwhals/dataframe.py
> +        See Also: `tail`, `glimpse`, `slice`
I don't this we have these yet, shall we remove this?

2024-03-29 11:18 UTC, MarcoGorelli commented on narwhals/dataframe.py
> +                       Accepts column selector input.
We don't yet have column selectors in Narwhals, let's remove this for now

2024-03-29 11:18 UTC, MarcoGorelli commented on narwhals/dataframe.py
> +            └─────┘
let's remove this one

2024-03-29 15:21 UTC, frnmst commented
I think I fixed everything

2024-03-30 10:25 UTC, MarcoGorelli approved these changes
Thank you @frnmst ! Seriously good docstrings here, well done!

Little tip - I'd suggest making a new branch for each new PR (rather than opening PRs from `main`), it just makes it a bit easier to review

![](https://i.fluffy.cc/g6TR0RVJMJ4f5nWrDR39tNrddc3gNSdm.gif)

2024-03-30 10:29 UTC, MarcoGorelli commented
Also, I removed some `doctest skip`s, as the doctests pass without them. For group-by, we can get a consistent output by adding a `sort`

2024-03-30 10:30 UTC, merged

2024-03-30 13:28 UTC, frnmst commented
> Thank you @frnmst ! Seriously good docstrings here, well done!
> 
> Little tip - I'd suggest making a new branch for each new PR (rather than opening PRs from `main`), it just makes it a bit easier to review


Ok, will do


> Also, I removed some `doctest skip`s, as the doctests pass without them. For group-by, we can get a consistent output by adding a `sort`

Ok, I'll keep that in mind for the next docstrings